#C:\Python27\python.exe
'''
Mary Qiu
Programmer: mq1418

Description: A sentence generator for people who have celebrity crushes.
The sentence is generated by the user's name, the name of their favorite celebrity,
and the number they will input.

'''

from __future__ import print_function
import os


def getName():
    ''' Gets the user's name '''
    uName = raw_input('What is your name? ')
    return uName

def getCelName():
    ''' Gets the name of the user's favorite celebrity '''
    cName = raw_input('Enter the name of your favorite celebrity: ')
    return cName

def getNum():
    ''' Gets a number from the user's input '''
    print('Type 0 to quit the game. Type a number 1 - 3 for message.')
    num = int(raw_input('Enter a number: '))
    return num

def displayMsg(uName, cName, num):
   ''' Displays a message based on the  '''
   if(num == 1):
       print(uName + ' likes ' + cName + '!')
   elif(num == 2):
       print(uName + ' wants to hug ' + cName + '!')
   elif(num == 3):
       print(cName + ' kissed ' + uName + '!' )
   elif(num == 0):
       exit
   else:
       print('Invalid number')
       num2 = getNum()
       displayMsg(uName,cName,num2)

def gameMenu():
    uName = getName()
    cName = getCelName()
    num = getNum()
    displayMsg(uName, cName, num)
        

def main():
    gameMenu()
    os.system("pause") 
main()
